name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      id: npm-audit
      run: |
        echo "## NPM Audit Results" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        npm audit --json > audit.json || true
        npm audit >> $GITHUB_STEP_SUMMARY || true
        echo '```' >> $GITHUB_STEP_SUMMARY
        
        # Check for high/critical vulnerabilities
        HIGH_VULNS=$(cat audit.json | jq -r '.metadata.vulnerabilities | .high + .critical' || echo "0")
        echo "High/Critical vulnerabilities found: $HIGH_VULNS"
        
        if [ "$HIGH_VULNS" -gt 0 ]; then
          echo "::warning::Found $HIGH_VULNS high/critical vulnerabilities"
          echo "### ⚠️ Found $HIGH_VULNS high/critical vulnerabilities" >> $GITHUB_STEP_SUMMARY
          exit 1
        else
          echo "### ✅ No high/critical vulnerabilities found" >> $GITHUB_STEP_SUMMARY
        fi
      continue-on-error: true
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript-typescript
        config-file: ./.github/codeql/codeql-config.yml
      continue-on-error: true
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      continue-on-error: true
    
    - name: Upload audit results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: npm-audit-report
        path: audit.json
        retention-days: 30